version: '3.5'
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mom
      - PG_DATA=/var/lib/postgresql/data/
    ports:
      - 5432:5432
    volumes:
      - ./.docker/db/:/var/lib/postgresql/data/
    networks:
      - mom_network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./.docker/pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - mom_network
    restart: unless-stopped

networks:
  mom_network:
    name: mom_network
